name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  validate:
    name: Validate Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-release-

      - name: Format Check
        run: cargo fmt --all -- --check

      - name: Clippy Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build Check
        run: cargo build --all-targets --all-features

      - name: Run Tests
        run: cargo test --all-targets --all-features

  build-release:
    name: Build Release Binaries
    needs: validate
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            artifact_name: ciphern
            asset_name: ciphern-linux-x86_64
          - os: windows-latest
            artifact_name: ciphern.exe
            asset_name: ciphern-windows-x86_64.exe
          - os: macos-latest
            artifact_name: ciphern
            asset_name: ciphern-macos-x86_64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target
          key: ${{ runner.os }}-cargo-build-${{ matrix.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-${{ matrix.os }}-

      - name: Build Release
        run: cargo build --release --locked

      - name: Create Artifact
        run: |
          mkdir -p release
          cp target/release/${{ matrix.artifact_name }} release/${{ matrix.asset_name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: release/${{ matrix.asset_name }}
          compression-level: 9
          retention-days: 30

  gitee-release:
    name: Create Gitee Release
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Gitee Release
        uses: actions-cool/gitee-release@v1
        with:
          version: ${{ steps.version.outputs.VERSION }}
          files: artifacts/**
          desc: Release v${{ steps.version.outputs.VERSION }}
